version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=:${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/srv/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  youtrack:
    image: jetbrains/youtrack:2020.2.7479
    container_name: "youtrack"
    volumes:
      - /srv/youtrack/data:/opt/youtrack/data
      - /srv/youtrack/conf:/opt/youtrack/conf
      - /srv/youtrack/logs:/opt/youtrack/logs
      - /srv/youtrack/backups:/opt/youtrack/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.youtrack.loadbalancer.server.port=8080"
      - "traefik.http.routers.youtrack.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.youtrack.entrypoints=websecure"
      - "traefik.http.routers.youtrack.tls.certresolver=myresolver"
